const projectsData: Record<string, any> = {
  'safestreet-vision': {
    category: "AI/ML • COMPUTER VISION",
    title: "SafeStreet Vision - Real-time Object Detection",
    appDisplayTitle: "Platform Overview",
    appDisplaySubtitle: "Web client showcase",
    appDisplayImages: [{ type: 'image', url: "/image/SafeStreetVision_display.png" }, { type: 'image', url: "/image/SafeStreetVision_display2.png" }],
    interfaceFocusLabel: "INTERFACE FOCUS",
    interfaceFocusTitle: "Real-Time Inference",
    interfaceFocusDesc: "Access webcam directly from the browser with bilingual support (EN/ID) and dynamic bounding box labels.",
    performanceLabel: "PERFORMANCE",
    performanceTitle: "Optimized ONNX Model",
    performanceDesc: "Exported PyTorch model to ONNX, verifying robust performance and low deviation for deployment.",
    productEvidenceTitle: "Product Evidence",
    productEvidenceSubtitle: "Object detection workflow through the web application",
    productEvidences: [{ type: 'video', url: "/vidio/SafeStreetVision.mp4" },
    { type: 'image', url: "/image/SafeStreetVision_test.png", fit: 'contain' },
    { type: 'image', url: "/image/SafeStreetVision_test2.jpeg", fit: 'contain' },
    ],
    primaryRole: "Machine Learning Engineer",
    additionalScopeLabel: "ADDITIONAL SCOPE",
    additionalScope: "API Development & Frontend Integration",
    collaboration: "individual project",
    status: "Completed",
    contextChallenge: "SafeStreet Vision is an end-to-end machine learning project designed to perform real-time object detection for road damage and motorcycle helmet usage. The primary challenge was addressing thin and low-contrast crack geometry, handling domain variation across multiple source datasets, and combining distinct tasks (road anomaly vs helmet detection) into a single efficient model.",
    processApproach: "Acting as the Machine Learning Engineer, I designed a comprehensive data pipeline to merge over 13,000 images and 35,000 annotations from various sources. I utilized YOLOv8 for model training, followed by ONNX export for optimized inference. A FastAPI backend was built to handle image and video-frame inference, seamlessly integrated with a Next.js frontend via Docker Compose.",
    resultImpact: "The model achieved an mAP@50 of 0.802 on the validation set and 0.789 on the test set across 9 classes. The system delivers rapid predictions with a max confidence delta of 0.0056 and box coordinate delta of 1.49px between PyTorch and ONNX, ensuring reliable real-time performance on deployed environments.",
    keyHighlights: [
      { title: "End-to-End CV Pipeline", desc: "Built a complete pipeline from dataset engineering and merging to YOLOv8 training and ONNX export." },
      { title: "Containerized Architecture", desc: "Orchestrated FastAPI backend and Next.js frontend using Docker Compose for seamless deployment." }
    ],
    technologies: ['Python', 'YOLOv8', 'FastAPI', 'ONNX', 'Next.js', 'Docker', 'OpenCV', 'PyTorch'],
    sourceCodeText: "Source Code",
    sourceCodeUrl: "https://github.com/rakhamaulanaeclone/safestreet-vision",

  },
  'lokalkeren': {
    category: "WEB APP • E-COMMERCE",
    title: "LokalKeren - Platform Direktori & E-commerce UMKM",
    appDisplayTitle: "Platform Interface",
    appDisplaySubtitle: "Optimized user experience across mobile and desktop devices.",
    appDisplayImages: [{ type: 'image', url: "/image/LokalKeren! - Pitch1.png" },],
    interfaceFocusLabel: "USER EXPERIENCE",
    interfaceFocusTitle: "Smart Discovery & AI Assistance",
    interfaceFocusDesc: "Location-based search and real-time operational filters (Haversine query), paired with a contextual AI chatbot to help users evaluate and choose local businesses.",
    performanceLabel: "SYSTEM ARCHITECTURE",
    performanceTitle: "Full-Stack E-Commerce",
    performanceDesc: "End-to-end order flow integrated with PostgreSQL database and analytics dashboard for local business owners.",
    productEvidenceTitle: "Location-Based E-Commerce Flow",
    productEvidenceSubtitle: "Integrated map features for smart discovery, checkout, and live order tracking.",
    productEvidences: [{ type: 'image', url: "/image/LokalKeren! - Pitch2.png" }],
    primaryRole: "Full Stack Developer",
    additionalScopeLabel: "ADDITIONAL ROLE",
    additionalScope: "Scrum Master",
    collaboration: "Team (Web In Action 2025)",
    status: "Completed",
    contextChallenge: "LokalKeren was born to address low visibility of local small businesses (UMKM), static and non-interactive directories like digital phone books, and the gap in modern user experience that now demands smart recommendations and integrated online transaction facilities within a single platform.",
    processApproach: "Built with Next.js App Router and Prisma ORM, we integrated a contextual AI chatbot and established robust transaction flows using PostgreSQL, seamlessly tied together with a unified role-based authentication system.",
    resultImpact: "The platform now delivers a smart discovery experience (location & operating hours filters), persistent shopping cart with Zustand, advanced checkout with Leaflet maps, and a business dashboard displaying analytics (revenue, best-selling products) and real-time notifications.",
    keyHighlights: [
      { title: "AI Integration", desc: "Leveraged Gemini AI API to build a contextual chatbot assistant (RAG) that understands local business data, and to generate on-demand sentiment summaries from user reviews." },
      { title: "Full-Stack E-commerce Flow", desc: "Persistent shopping cart with Zustand, structured real transactions in PostgreSQL via Prisma, and route tracking system (Maps)." },
      { title: "Role-Based Dashboard", desc: "Unified authentication for customers and business owners with business analytics (Recharts), real-time order management, and product CRUD." }
    ],
    technologies: ['Next.js 14', 'React', 'TypeScript', 'Tailwind CSS', 'Prisma', 'PostgreSQL', 'Chatbot Gemini API', 'Zustand'],
    sourceCodeText: "Source Code",
    sourceCodeUrl: "https://github.com/Ahnafprojects/direktori-umkm",
    demoText: "Live Demo",
    demoUrl: "https://lokalkeren.netlify.app"
  },
  'peminjaman-ruangan': {
    category: "WEB APP • MANAGEMENT SYSTEM",
    title: "Peminjaman Ruangan - Campus Space Reservation",
    appDisplayTitle: "Application Displays",
    appDisplaySubtitle: "High-fidelity mobile client showcase & interface walkthrough",
    appDisplayImages: [{ type: 'image', url: "/peminjaman-ruangan/app-display.png" }],
    interfaceFocusLabel: "BOOKING FOCUS",
    interfaceFocusTitle: "Smart Booking System",
    interfaceFocusDesc: "Validasi ketersediaan dan bentrokan jadwal secara cerdas untuk mencegah overlapping pemesanan ruangan.",
    performanceTitle: "Robust Architecture",
    performanceDesc: "Integrasi API terstruktur antara frontend React + Vite dengan backend ASP.NET Core dan PostgreSQL.",
    productEvidenceTitle: "Product Evidence",
    productEvidenceSubtitle: "Comprehensive mobile workflows & interactive pipeline",
    productEvidences: [{ type: 'image', url: "/peminjaman-ruangan/metrics-dashboard.png" }],
    primaryRole: "Backend & Frontend Dev",
    additionalScopeLabel: "OTHER SCOPE",
    additionalScope: "API Alignment & Auth",
    collaboration: "Tim Proyek Akademik",
    status: "Completed",
    contextChallenge: "Proses peminjaman ruangan kampus membutuhkan validasi jadwal yang ketat, manajemen role pengguna, approval admin, dan sistem penyimpanan riwayat data yang solid agar tidak mudah hilang.",
    processApproach: "Membangun API menggunakan ASP.NET Core 10.0 dan Entity Framework Core, berpasangan dengan React + Vite di frontend. Saya menyelaraskan UserRole dan BookingStatus, menghubungkan autentikasi, serta mendukung API dengan validasi DTO, Swagger, CORS, dan endpoint approval status.",
    resultImpact: "Terciptanya Smart Booking System yang mencegah tabrakan jadwal dengan validasi waktu real-time. Keamanan dan integritas data (Data Safety) dipastikan dengan implementasi fitur Soft Delete pada PostgreSQL untuk menjaga rekam jejak audit peminjaman ruangan.",
    keyHighlights: [
      { title: "Smart Booking System", desc: "Validasi otomatis waktu mulai dan selesai, serta pencegahan tabrakan peminjaman di slot waktu yang sama (Availability Check)." },
      { title: "Data Safety (Soft Delete)", desc: "Mekanisme API DELETE yang hanya mengatur flag is_deleted = true tanpa menghapus baris di database, sehingga riwayat audit tetap utuh." },
      { title: "Robust Tech Stack", desc: "Arsitektur frontend React + Vite yang terhubung secara mulus ke API ASP.NET Core dan PostgreSQL via Entity Framework." }
    ],
    technologies: ['React', 'Vite', 'ASP.NET Core', 'C#', 'Entity Framework', 'PostgreSQL', 'Swagger']
  },
  'talenthub-mobile': {
    category: "MOBILE APP • ATS",
    title: "TalentHub - Mobile ATS Ecosystem",
    appDisplayTitle: "Application Displays",
    appDisplaySubtitle: "High-fidelity mobile client showcase & interface walkthrough",
    appDisplayImages: [{ type: 'image', url: "/image/Talenthub_display.jpg" }, { type: 'image', url: "/image/Talenthub_display2.jpg" }],
    interfaceFocusLabel: "PRODUCT FOCUS",
    interfaceFocusTitle: "Multi-Role ATS Ecosystem",
    interfaceFocusDesc: "Delivers a seamless mobile experience (UI/UX) for three distinct roles Applicant, HR Recruiter, and Hiring Manager with securely separated access control and user flows.",
    performanceLabel: "CORE FEATURE",
    performanceTitle: "Comprehensive Apply Flow",
    performanceDesc: "Developed a seamless candidate application process featuring dynamic job filtering and strict real-time profile eligibility validation before submission.",
    primaryRole: "Mobile Developer (Flutter)",
    additionalScopeLabel: "ADDITIONAL SCOPE",
    additionalScope: "",
    collaboration: "Team Project (Cross-functional)",
    status: "Active Development • Sprint 3",
    contextChallenge: "Internal recruitment processes are often unstructured, with candidate application data scattered across multiple platforms like email, WhatsApp, spreadsheets without a single source of truth. The main challenge was designing a unified mobile-based ATS (Applicant Tracking System) ecosystem capable of serving three distinct user roles: Applicant, HR Recruiter, and Hiring Manager, within one centralized, standardized, and crash-free application.",
    processApproach: "As the lead Mobile Developer, I was responsible for building the interface and frontend logic using Flutter. On the Applicant side, I implemented the Job Discovery flow (search, filter, vacancy details) through the complex Apply Flow along with application status management. On the HR side, I built Job Posting Management with reactive forms (rich text, auto-save debounce) and a Kanban Pipeline interface for interview scheduling, complete with strict rollback logic.",
    resultImpact: "The application successfully unified the entire recruitment cycle into a single seamless mobile platform. With comprehensive state handling on every page, the app delivers a responsive and informative user experience. This directly supports the business target of achieving time to hire under 25 days and ensuring a 0% critical defect rate on core features.",
    keyHighlightsTitle: "TECHNICAL HIGHLIGHTS",
    keyHighlights: [
      { title: "End-to-End Mobile Flow", desc: "Built the complete interface lifecycle from start to finish from job posting creation by HR, search & application submission by candidates, to status tracking (My Applications & Saved Jobs)." },
      { title: "Comprehensive Apply Flow", desc: "Developed a seamless candidate application process featuring dynamic job filtering and strict real-time profile eligibility validation." },
      { title: "Reactive Forms & API Integration", desc: "Implemented complex forms with Rich Text Editor, dynamic inputs, and strict validation. Used 1-second debounce for real-time auto-save to ensure HR data is never lost during job posting creation." }
    ],
    technologies: ['Flutter', 'Dart', 'REST API', 'Dio', 'State Management', 'Flutter Secure Storage'],
    sourceCodeText: "Source Code",
    sourceCodeUrl: "https://github.com/pens-pbl/talenthub-mobile",
    playStoreText: "Google Play",
    playStoreUrl: "https://play.google.com/store/apps/details?id=id.ac.pens.it.talenthub&pcampaignid=web_share",
    contributions: [
      { title: "Mobile App Ownership:", desc: "Implemented the complete end-to-end frontend architecture in Flutter, utilizing the BLoC (Business Logic Component) pattern for scalable and predictable state management, alongside secure authentication and role-based UI rendering." },
      { title: "Cross-Functional Coordination:", desc: "Collaborated closely with UI/UX designers to translate high-fidelity mockups into pixel-perfect UI components and responsive screens. Coordinated directly with Backend developers (.NET) to align API contracts and handle complex JSON data structures efficiently." },
      { title: "Advanced Interactive UI:", desc: "Built complex interface interactions for dual workflows, including multi-step Job Posting forms with debounce auto-save for HR, and dynamic search, filtering, and application submission flows for Candidates." },
      { title: "State & Error Handling:", desc: "Leveraged BLoC events and states to gracefully handle loading, empty, and error scenarios across all screens. Integrated debounce capabilities for real-time auto-saving to prevent data loss during the job posting process.." }
    ],
    systemDeployment: {
      desc: "The current deployment keeps the product surfaces, application API, and data layer independently maintainable.",
      points: [
        { title: "PRODUCT SURFACES:", desc: "Flutter mobile app" },
        { title: "APPLICATION:", desc: ".NET API" },
        { title: "DATA:", desc: "PostgreSQL" },
        { title: "TECHNOLOGY STACK:", desc: "Flutter, Dart, BLoC, Dio, Secure Storage, .NET, PostgreSQL, Docker" }
      ]
    },
    achievedResults: [
      { title: "Role-Aware Mobile Workflows:", desc: "Candidates can discover vacancies while recruiters can create and manage job postings through workflows designed for their respective roles." },
      { title: "Robust Client-Side Architecture:", desc: "The mobile application consistently maintains data integrity through dynamic form validation, real-time auto-save mechanisms, and secure token rotation handlers driven by the BLoC state container." },
      { title: "End-To-End Recruitment Flow:", desc: "Delivered a highly responsive user experience connecting candidate job discovery with comprehensive internal HR vacancy management." }
    ]
  }
};

export default projectsData;
